alter table public.books add column if not exists publisher text;

create table if not exists public.book_value_history (
  id bigint generated by default as identity primary key,
  book_id uuid not null references public.books(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  value numeric not null default 0,
  recorded_at timestamptz not null default now()
);

create index if not exists book_value_history_book_recorded_idx
  on public.book_value_history(book_id, recorded_at);

alter table public.book_value_history enable row level security;

drop policy if exists "Users can read own book value history" on public.book_value_history;
create policy "Users can read own book value history"
  on public.book_value_history for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own book value history" on public.book_value_history;
create policy "Users can insert own book value history"
  on public.book_value_history for insert
  with check (auth.uid() = user_id);

create or replace function public.record_book_value_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.current_value is distinct from old.current_value then
    insert into public.book_value_history(book_id, user_id, value)
    values (new.id, new.user_id, coalesce(new.current_value, 0));
  end if;
  return new;
end;
$$;

drop trigger if exists books_value_history on public.books;
create trigger books_value_history
after insert or update of current_value on public.books
for each row execute function public.record_book_value_history();

insert into public.book_value_history(book_id, user_id, value, recorded_at)
select b.id, b.user_id, coalesce(b.current_value, 0), coalesce(b.created_at, now())
from public.books b
where not exists (
  select 1 from public.book_value_history h where h.book_id = b.id
);
